networks:
  medical-network:
    name: medical-network

services:
  # Regulator Peer
  peer0.regulator.medical-network.com:
    container_name: peer0.regulator.medical-network.com
    image: hyperledger/fabric-peer:2.5.3
    platform: linux/amd64
    environment:
      - DOCKER_API_VERSION=1.44
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-config
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.regulator.medical-network.com
      - CORE_PEER_ADDRESS=peer0.regulator.medical-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.medical-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_MODE=dev
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.medical-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.medical-network.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.regulator.medical-network.com:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_BCCSP_DEFAULT=SW
      - CORE_PEER_BCCSP_SW_SECURITY=256
      - CORE_PEER_BCCSP_SW_HASH=SHA2
      - CORE_PEER_BCCSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../config:/etc/hyperledger/fabric-config
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../crypto-config/peerOrganizations/regulator.medical-network.com/peers/peer0.regulator.medical-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/regulator.medical-network.com/peers/peer0.regulator.medical-network.com/tls/:/etc/hyperledger/fabric/tls
      - ../crypto-config/peerOrganizations/regulator.medical-network.com/users:/etc/hyperledger/fabric/users
      - ../channel-artifacts:/etc/hyperledger/configtx
      - ../crypto-config/ordererOrganizations/medical-network.com/orderers/orderer0.medical-network.com/tls/ca.crt:/etc/hyperledger/orderer-tls/ca.crt
      - ../crypto-config/peerOrganizations/hospital1.medical-network.com/peers/peer0.hospital1.medical-network.com/tls/ca.crt:/etc/hyperledger/peer-tls/hospital1/ca.crt
      - ../crypto-config/peerOrganizations/hospital2.medical-network.com/peers/peer0.hospital2.medical-network.com/tls/ca.crt:/etc/hyperledger/peer-tls/hospital2/ca.crt
      - ${HOME}/.docker/run/docker.sock:/host/var/run/docker.sock
      - ${HOME}/.docker/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/opt/chaincode-package
      - ../external-builder:/opt/hyperledger/external-builder
      - ../../chaincode/medical-records/collections_config.json:/tmp/collections_config.json
      - ../../data/peer0.regulator:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "11051:7051"
      - "9443:9443"
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "peer", "node", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Hospital 1 Peer
  peer0.hospital1.medical-network.com:
    container_name: peer0.hospital1.medical-network.com
    image: hyperledger/fabric-peer:2.5.3
    platform: linux/amd64
    environment:
      - DOCKER_API_VERSION=1.44
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-config
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.hospital1.medical-network.com
      - CORE_PEER_ADDRESS=peer0.hospital1.medical-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.medical-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_MODE=dev
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital1.medical-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital1.medical-network.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.hospital1.medical-network.com:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_LOCALMSPID=HospitalMSP1
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_BCCSP_DEFAULT=SW
      - CORE_PEER_BCCSP_SW_SECURITY=256
      - CORE_PEER_BCCSP_SW_HASH=SHA2
      - CORE_PEER_BCCSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../config:/etc/hyperledger/fabric-config
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../crypto-config/peerOrganizations/hospital1.medical-network.com/peers/peer0.hospital1.medical-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.medical-network.com/peers/peer0.hospital1.medical-network.com/tls/:/etc/hyperledger/fabric/tls
      - ../crypto-config/peerOrganizations/hospital1.medical-network.com/users:/etc/hyperledger/fabric/users
      - ../channel-artifacts:/etc/hyperledger/configtx
      - ../crypto-config/ordererOrganizations/medical-network.com/orderers/orderer0.medical-network.com/tls/ca.crt:/etc/hyperledger/orderer-tls/ca.crt
      - ../crypto-config/peerOrganizations/hospital2.medical-network.com/peers/peer0.hospital2.medical-network.com/tls/ca.crt:/etc/hyperledger/peer-tls/hospital2/ca.crt
      - ../crypto-config/peerOrganizations/research.medical-network.com/peers/peer0.research.medical-network.com/tls/ca.crt:/etc/hyperledger/peer-tls/research/ca.crt
      - ../crypto-config/peerOrganizations/regulator.medical-network.com/peers/peer0.regulator.medical-network.com/tls/ca.crt:/etc/hyperledger/peer-tls/regulator/ca.crt
      - ${HOME}/.docker/run/docker.sock:/host/var/run/docker.sock
      - ${HOME}/.docker/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/opt/chaincode-package
      - ../external-builder:/opt/hyperledger/external-builder
      - ../../chaincode/medical-records/collections_config.json:/tmp/collections_config.json
      - ../../data/peer0.hospital1:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "12051:7051"
      - "9444:9443"
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "peer", "node", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Hospital 2 Peer
  peer0.hospital2.medical-network.com:
    container_name: peer0.hospital2.medical-network.com
    image: hyperledger/fabric-peer:2.5.3
    platform: linux/amd64
    environment:
      - DOCKER_API_VERSION=1.44
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-config
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.hospital2.medical-network.com
      - CORE_PEER_ADDRESS=peer0.hospital2.medical-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.medical-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_MODE=dev
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital2.medical-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital2.medical-network.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.hospital2.medical-network.com:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_LOCALMSPID=HospitalMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_BCCSP_DEFAULT=SW
      - CORE_PEER_BCCSP_SW_SECURITY=256
      - CORE_PEER_BCCSP_SW_HASH=SHA2
      - CORE_PEER_BCCSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../config:/etc/hyperledger/fabric-config
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../crypto-config/peerOrganizations/hospital2.medical-network.com/peers/peer0.hospital2.medical-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital2.medical-network.com/peers/peer0.hospital2.medical-network.com/tls/:/etc/hyperledger/fabric/tls
      - ../crypto-config/peerOrganizations/hospital2.medical-network.com/users:/etc/hyperledger/fabric/users
      - ../channel-artifacts:/etc/hyperledger/configtx
      - ../crypto-config/ordererOrganizations/medical-network.com/orderers/orderer0.medical-network.com/tls/ca.crt:/etc/hyperledger/orderer-tls/ca.crt
      - ${HOME}/.docker/run/docker.sock:/host/var/run/docker.sock
      - ${HOME}/.docker/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/opt/chaincode-package
      - ../external-builder:/opt/hyperledger/external-builder
      - ../../chaincode/medical-records/collections_config.json:/tmp/collections_config.json
      - ../../data/peer0.hospital2:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "13051:7051"
      - "9445:9443"
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "peer", "node", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Research Organization Peer
  peer0.research.medical-network.com:
    container_name: peer0.research.medical-network.com
    image: hyperledger/fabric-peer:2.5.3
    platform: linux/amd64
    environment:
      - DOCKER_API_VERSION=1.44
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-config
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/production/snapshots
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.research.medical-network.com
      - CORE_PEER_ADDRESS=peer0.research.medical-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.medical-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_MODE=dev
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.research.medical-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.research.medical-network.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.research.medical-network.com:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_LOCALMSPID=ResearchOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_BCCSP_DEFAULT=SW
      - CORE_PEER_BCCSP_SW_SECURITY=256
      - CORE_PEER_BCCSP_SW_HASH=SHA2
      - CORE_PEER_BCCSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../config:/etc/hyperledger/fabric-config
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../crypto-config/peerOrganizations/research.medical-network.com/peers/peer0.research.medical-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/research.medical-network.com/peers/peer0.research.medical-network.com/tls/:/etc/hyperledger/fabric/tls
      - ../crypto-config/peerOrganizations/research.medical-network.com/users:/etc/hyperledger/fabric/users
      - ../channel-artifacts:/etc/hyperledger/configtx
      - ../crypto-config/ordererOrganizations/medical-network.com/orderers/orderer0.medical-network.com/tls/ca.crt:/etc/hyperledger/orderer-tls/ca.crt
      - ${HOME}/.docker/run/docker.sock:/host/var/run/docker.sock
      - ${HOME}/.docker/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/opt/chaincode-package
      - ../external-builder:/opt/hyperledger/external-builder
      - ../../chaincode/medical-records/collections_config.json:/tmp/collections_config.json
      - ../../data/peer0.research:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "14051:7051"
      - "9446:9443"
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "peer", "node", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5

  medicalcc:
    container_name: medicalcc
    image: node:18-alpine
    working_dir: /chaincode
    environment:
      - CORE_CHAINCODE_ID_NAME=medicalcc
    volumes:
      - ../../chaincode/medical-records:/chaincode
    command: >
      sh -c "
      npm install &&
      npm start -- --peer.address=peer0.regulator.medical-network.com:7052
      "
    networks:
      - medical-network
